### ISSUE TITLE
Arch Linux 常用软件

### ISSUE THREAD

**Issue by KiteAB** [KiteAB/blog-comments#5]
https://kiteab.ga/posts/arch-linux-常用软件/

**Comment by herschel-ma** [comment]
hello,我是来自B站向你要女装照片的Herschel,先声明，虽然我工作了，但是个菜鸡，不准嘲笑我！我来送出我的"处"评论。另外，申请个友链？herschel-ma.github.io

**Comment by KiteAB** [comment]
> @herschel-ma
> hello,我是来自B站向你要女装照片的Herschel,先声明，虽然我工作了，但是个菜鸡，不准嘲笑我！我来送出我的"处"评论。另外，申请个友链？herschel-ma.github.io

友链请去友链界面申请
